### ISSUE TITLE
Suggestion: Add Process Hacker

### ISSUE THREAD

**Issue by colorburst** [dsasmblr/game-hacking#2]
https://wj32.org/processhacker/index.php

It's a GPL alternative to Process Explorer with a familiar look and feel and a very rich feature set. I have switched to it from PE a few years ago and using it has always been an overwhelmingly positive experience. It may very well be one of the best open-source Windows system tools out there.

**Comment by dsasmblr** [comment]
Thanks for sharing! Added to the list. =)
