### ISSUE TITLE
BlackBone library

### ISSUE THREAD

**Issue by DKingCN** [dsasmblr/game-hacking#3]
Im currently using a library source called (BlackBone)[https://github.com/DarthTon/Blackbone]. It provides 
varieties features including a driver method for anti-detection, which is powerful af. The only pain is that it's a C++ library so I cant just compile the codes into C#. But it's still cool.

Please check and decide whether this is good enough to be in the list.

**Comment by dsasmblr** [comment]
Thanks for sharing! Yes, this is absolutely worth adding. I also added Xenos to the tools section, so that and Blackbone are now a part of the list. =)
