### ISSUE TITLE
Some URLs for your great list :) 

### ISSUE THREAD

**Issue by FransBouma** [dsasmblr/game-hacking#4]
- MinHook, a hooking library I use myself a lot: https://github.com/TsudaKageyu/minhook
- My Injectable Generic Camera System repo for creating custom camera tools for games: https://github.com/FransBouma/InjectableGenericCameraSystem (also contains small tools, like a dll injector, as well-known ones are often blacklisted by windows defender) 
- Reshade source code: https://github.com/crosire/reshade While not directly hacking related, it contains a wealth of information how to intercept DX/OpenGL api's and perform your own code instead or use it as a trigger for your own code (e.g. call your own code at Present time when a frame is rendered)

**Comment by dsasmblr** [comment]
Thanks for your contributions! I've added all of them to the list. I'm looking forward to trying out your camera system soon. =)
