### ISSUE TITLE
Some more (Mostly java) links

### ISSUE THREAD

**Issue by Col-E** [dsasmblr/game-hacking#5]
Here's some neat java tools I use pretty often:

* [Deobfuscator](https://github.com/java-deobfuscator/deobfuscator)
  * >This is an all-in-one Java deobfuscator which will deobfuscate code obfuscated by most obfuscators available on the market.
      * _Supported Obfuscators:_  Allatori, DashO, SkidSuite, Smoke, Stringer, Zelix + generic features shared by many obfuscators
* [Helios](https://github.com/helios-decompiler/standalone-app)
  * >Helios is an all-in-one Java reverse engineering tool. It features integration with the latest up-to-date decompilers.
     * _Decompilers:_  Krakatau, Fernflower, CFR, Procyon, Javap
     * All decompiler settings available through the UI
* [Recaf](https://github.com/Col-E/Recaf)
  * >An easy to use modern Java bytecode editor. 
     * Use to edit the binary of java games and such without needing a hex editor or without having to decompile and recompile classes. 
  * _Disclosure: I made this_
* [JRemapper](https://github.com/Col-E/JRemapper)
  * >An easy to use GUI for remappin classes, methods, and fields of compiled java programs.
     * Makes making mappings for obfuscated programs a breeze. Helpful for cases like Minecraft.
  * _Disclosure: I made this_

Also since I saw you added [a portal 2 hack](https://github.com/RedMage1993/Portal2Hack) there's an open source [Source Engine](https://github.com/nullifiedcat/cathook) hack that works for multiple games. Looks like on non-main branches there's some activity.

**Comment by dsasmblr** [comment]
Thanks for your contributions! I've added them to the list. =)
